#!name=电信余量请求体获取
#!desc=开启脚本以及mitm等开关，配合电信余量使用

[Script]
请求体获取 = type=http-request,script-path=请求体获取.js,pattern=^https?:\/\/czapp\.bestpay\.com\.cn,max-size=131072,requires-body=true,timeout=10,script-update-interval=86400,debug=true,enable=true
电信余量 = type=cron,script-path=https://raw.githubusercontent.com/QGCliveDavis/Module/main/SHADOWROCKET/10000.js,cronexpr="*/5 * * * *",timeout=10,script-update-interval=86400,enable=true]
[MITM]
hostname = czapp.bestpay.com.cn